version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend